#選擇golang版本
FROM golang:1.15.6-alpine
LABEL maintainer="andy@accuhit.net"

#安裝git
#RUN apk add --no-cache git

#RUN cd /
#當前工作目錄
#WORKDIR /project
#ADD project/main.go /project
#進到資料夾 生成執行檔
#RUN cd /project && go build
#預設port7000
#EXPOSE 7000
#執行執行檔
#ENTRYPOINT ./project
